### ISSUE TITLE
Add Custom Syntax Highlighting

### ISSUE THREAD

**Issue by yeradis** [sergiandreplace/sergiandreplace.com#3]
In order for Custom Syntax Highlighting to work

first at the CLI:

```bash
hugo gen chromastyles --style=native > static/syntax.css
```

then at `config.toml`, the new options to add, are  : `pygmentsUseClasses=true`  and `pygmentsCodeFences=true`, so later we can specify where is the `syntax.css` so the `chroma` style generated with `hugo gen chroma...` can be applied

```toml
pygmentsUseClasses=true
pygmentsCodeFences=true
```

and

```toml
[params.customCSS]
url = "/syntax.css"
```
